server:
  port: 8080

spring:
  profiles:
    active: local

odsay:
  api-key: ${ODSAY_API_KEY}

ddareungi:
  api-key: ${DDAREUNGI_API_KEY}

tago:
  api-key: ${TAGO_API_KEY}
  city-code: 11   # 서울특별시 지역코드

naver:
  client-id: ${NAVER_CLIENT_ID}
  client-secret: ${NAVER_CLIENT_SECRET}
  search:
    client-id: ${NAVER_SEARCH_CLIENT_ID:}
    client-secret: ${NAVER_SEARCH_CLIENT_SECRET:}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
